### ISSUE TITLE
Shall we clone 3rdparties over ssh?

### ISSUE THREAD

**Issue by shingarov** [janvrany/Tinyrossa#16]
If I am cloning Tinyrossa as myself, this means I already have a GH account.  However, everything in `3rdparty` is cloned over https.  A common situation is that I would be working on TR (or Pharo-ArchC or whatever) and do a change to MachineArithmetic; I would commit, only to be annoyed by being greeted by a username prompt when I try to push the commit (say, on a new branch).

**Comment by janvrany** [comment]
Fixed by PR #17.
